baseURL = '/blog/'
languageCode = 'en-us'
title = "Himel Das | Blog"
theme = 'PaperMod'
canonifyURLs = false  # ← Change to false
relativeURLs = false

[params]
  env = "production"
  description = "Thoughts on astrophysics, FOSS, and technology"
  author = "Himel Das"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = false

  [[params.socialIcons]]
    name = "email"
    url = "mailto:hello2himel@proton.me"
  
  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/hello2himel"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hello2himel"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"  # ← Use "/" not "../"
    weight = 10
  
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  
  [[menu.main]]
    name = "Tags"
    url = "/blog/tags/"
    weight = 30
  
  [[menu.main]]
    name = "Search"
    url = "/blog/search/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]